# Site settings
title: try.catchy.io
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  catchy.io find issues of your PHP apps and help you fix them quickly.
  Try us for free, we're developer friendly \(°v°).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://try.catchy.io" # the base hostname & protocol for your site
twitter_username: catchy_io
github_username:  catchy_io

# Build settings
markdown: kramdown
